services:
  mtproto-proxy:
    image: ghcr.io/kolsys/tg-proxy-light:latest
    build: .
    container_name: mtproto-proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - proxy-config:/data
    environment:
      # To generate a new 16-byte secret, run the following command in your terminal:
      # head -c 16 /dev/urandom | xxd -ps
      - SECRET=**************************
      # - WORKERS=2

volumes:
  proxy-config: